# Generated by Django 3.2.5 on 2021-08-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='bidsCount',
            field=models.IntegerField(default=0, help_text='counter bids  for this job'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='like_counts',
            field=models.IntegerField(default=0, help_text='counter likes  for this job'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='paymentTime',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='paymentType',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='paymentValue',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
